// Sample product data — mirrors DummyJSON shape (id, title, price, thumbnail, category, rating)
// Used as a fake data source before switching to the real API in day 3.

export const products = [
  {
    id: 1,
    title: "Bàn phím cơ Keychron K2",
    price: 1890000,
    thumbnail: "",
    category: "keyboards",
    rating: 4.8,
  },
  {
    id: 2,
    title: "Chuột Logitech MX Master 3",
    price: 2350000,
    thumbnail: "",
    category: "mice",
    rating: 4.9,
  },
  {
    id: 3,
    title: "Tai nghe Sony WH-1000XM5",
    price: 7490000,
    thumbnail: "",
    category: "headphones",
    rating: 4.7,
  },
  {
    id: 4,
    title: "Màn hình Dell U2422H 24\"",
    price: 5200000,
    thumbnail: "",
    category: "monitors",
    rating: 4.6,
  },
  {
    id: 5,
    title: "Webcam Logitech C920",
    price: 1650000,
    thumbnail: "",
    category: "webcams",
    rating: 4.5,
  },
  {
    id: 6,
    title: "Đèn để bàn BenQ ScreenBar",
    price: 1290000,
    thumbnail: "",
    category: "lighting",
    rating: 4.7,
  },
  {
    id: 7,
    title: "Hub USB-C Anker 7-in-1",
    price: 890000,
    thumbnail: "",
    category: "accessories",
    rating: 4.4,
  },
  {
    id: 8,
    title: "Lót chuột Artisan FX Zero XL",
    price: 750000,
    thumbnail: "",
    category: "mousepads",
    rating: 4.6,
  },
  {
    id: 9,
    title: "Tai nghe gaming Razer BlackShark V2",
    price: 1990000,
    thumbnail: "",
    category: "headphones",
    rating: 4.5,
  },
  {
    id: 10,
    title: "Bàn phím không dây Logitech MX Keys",
    price: 2890000,
    thumbnail: "",
    category: "keyboards",
    rating: 4.8,
  },
  {
    id: 11,
    title: "Màn hình LG 27UK850 4K",
    price: 8900000,
    thumbnail: "",
    category: "monitors",
    rating: 4.7,
  },
  {
    id: 12,
    title: "Giá đỡ laptop Rain Design mStand",
    price: 1490000,
    thumbnail: "",
    category: "accessories",
    rating: 4.6,
  },
];
